apiVersion: v1
kind: Service
metadata:
  name: ipfs-cluster
  namespace: ipfs
  labels:
    app: ipfs-cluster
  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: change.me.com
  
spec:
  #type: LoadBalancer
  type: ClusterIP
  selector:
    app: ipfs-cluster
  ports:
    - name: swarm
      targetPort: 4001
      port: 4001
      protocol: TCP
    - name: swarm-udp
      targetPort: 4002
      port: 4002
      protocol: TCP
    - name: ws
      targetPort: 8081
      port: 8081
      protocol: TCP
    - name: http
      targetPort: 8080
      port: 8080
      protocol: TCP
    - name: api-http
      targetPort: 9094
      port: 9094
      protocol: TCP
    - name: proxy-http
      targetPort: 9095
      port: 9095
      protocol: TCP
    - name: cluster-swarm
      targetPort: 9096
      port: 9096
      protocol: TCP
  