# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-config
  namespace: ipfs
type: Opaque
data:
  cluster-secret: MjFjYzYwNzU4YzZiZDNhNDkxM2MyYjJjMGFkOGMxM2M4NjBhOGUxMWVlNTYyMzY3ZWQyM2M2ZGI5YjQwZGVkYw==
  bootstrap-peer-priv-key: MTJEM0tvb1dITTRrTE53UzJGek41R3RHNURmeTloN2RMVFJzM3J0dUY5TmlSNG1qQnYzaAo=